---

#  +--------------------------------------------+
#  |                                            |
#  |    Demo-file for a docker-image-* repo.    |
#  |                                            |
#! |    ADJUST THIS FILE TO YOUR NEEDS !!!!     |
#  |                                            |
#  +--------------------------------------------+

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "src/main"
    schedule:
      interval: "weekly"
