# @file Dockerfile
# @brief Lorem ipsum dolor sit amet, consetetur sadipscing elitr.
#
# @description Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
# tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 
#
# === Example
#
# To build and run the image for testng purposes locally use ``docker build -t local/ubuntu:dev .``
# and ``docker run --rm local/ubuntu:dev``.
#
# == Prerequisites
#
# This image has been developed and tested with Docker version 24.0.2 on top of Ubuntu 22.10. 
#
# == See also
#
# Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod  tempor invidunt
# ut labore et dolore magna aliquyam erat, sed diam voluptua. 

FROM ubuntu:23.10
LABEL maintainer="sebastian@sommerfeld.io"
