# @file Makefile
# @brief ...
#
# @description ...
# todo ... write description and brief (above)
#
# == Prerequisites
#
# This image has been developed and tested with Docker version 24.0.2 on top of Ubuntu 22.10.
#
# == How to use this Makefile
#
# todo ... at least update the image names below


say_hello:
	echo "Hello World"
