Bash utility to assist with day to day tasks just like J.A.R.V.I.S. does for Iron Man.

image:{github-actions-url}/{job-generate-docs}/{badge}[Github Badge, link={github-actions-url}/{job-generate-docs}]
image:{github-actions-url}/{job-ci}/{badge}[Github Badge, link={github-actions-url}/{job-ci}]

* Github Repository -> {url-project}
* Documentation -> https://www.sommerfeld.io/docs/docker-images/{project-name}-docs/main
* Where to file issues -> {url-project}/issues

== About this project
This project assists with daily bash command and helps reducing time and overhead by automating some simple tasks like initializing a new link:https://antora.org[Antora] module.

Jarvis uses a modular achitecture to add new featues.

== How to use this project
To install this project you can simply use the bootstrap script `curl https://raw.githubusercontent.com/sebastian-sommerfeld-io/jarvis/main/src/main/install.sh | bash -`.

To use this project, just use the `jarvis` command from your bash.

NOTE: Keep in mind that this project was developed for Ubuntu.

== Risks and Technical Debts
Scale for Probability and Impact: Low, Medium and High

[cols="^1,2,5a,1,1,5a", options="header"]
|===
|# |Title |Description |Probability |Impact |Response
|{counter:usage} |- |- |- |- |-
|===

== Contact
Feel free to contact me via sebastian@sommerfeld.io or visit my website https://www.sommerfeld.io.
