---
name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - dependabot/**

permissions:
  contents: read

jobs:

  # ----- Commit stage --------------------------

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3

  lint-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run folderslint in container
        run: docker run -i --rm --volume "$(pwd):$(pwd)" --workdir "$(pwd)" sommerfeldio/folderslint:latest folderslint
        shell: bash

  lint-filenames:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ls-lint in container
        run: docker run -i --rm --volume "$(pwd):/data" --workdir "/data" lslintorg/ls-lint:1.11.0
        shell: bash

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: node_modules target

  # ----- Commit stage (docs) -------------------

  update-versions:
    runs-on: ubuntu-latest
    name: ${{ matrix.yml-file }}
    if: ${{ (github.actor != 'dependabot[bot]') }}
    needs: ['lint-yaml', 'lint-folders', 'lint-filenames', 'shellcheck']
    strategy:
      matrix:
        yml-file: ['docs/antora.yml']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: Print Branchname
        run: echo ${{github.ref}}
        shell: bash
      - name: Adjust version in ${{ matrix.yml-file }}
        uses: sebastian-sommerfeld-io/github-action-update-antora-yml@main
        with:
          git_ref: ${{github.ref}}
          file: ${{ matrix.yml-file }}
      - name: Run yamllint for ${{ matrix.yml-file }}
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ${{ matrix.yml-file }}
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: "[Actions Bot] update antora yml"

  generate-docs:
    runs-on: ubuntu-latest
    if: ${{ (github.actor != 'dependabot[bot]') }}
    needs: ['update-versions']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: Generate docs from source code
        run: docker run --rm --volume "$(pwd):/project" --workdir "/project" sommerfeldio/source2docs:rc docs
        shell: bash
      - name: README.adoc
        run: |
          TARGET_ADOC="README.adoc"
          cp docs/modules/ROOT/pages/index.adoc "$TARGET_ADOC"
          {
            echo
            echo "// +-------------------------------------------+"
            echo "// |                                           |"
            echo "// |    DO NOT EDIT DIRECTLY !!!!!             |"
            echo "// |                                           |"
            echo "// |    File is auto-generated by pipeline.    |"
            echo "// |    Contents are based on Antora docs.     |"
            echo "// |                                           |"
            echo "// +-------------------------------------------+"
          } >> "$TARGET_ADOC"
        shell: bash
      - name: LICENSE.adoc
        run: |
          TARGET_ADOC="LICENSE.adoc"
          cp docs/modules/ROOT/pages/license.adoc "$TARGET_ADOC"
          {
            echo
            echo "// +-------------------------------------------+"
            echo "// |                                           |"
            echo "// |    DO NOT EDIT DIRECTLY !!!!!             |"
            echo "// |                                           |"
            echo "// |    File is auto-generated by pipeline.    |"
            echo "// |    Contents are based on Antora docs.     |"
            echo "// |                                           |"
            echo "// +-------------------------------------------+"
          } >> "$TARGET_ADOC"
        shell: bash
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: "[Actions Bot] generate docs"

  # ----- Notifications -------------------------

  on-failure:
    runs-on: ubuntu-latest
    needs: [
      'update-versions',
      'generate-docs',
      'lint-yaml',
      'lint-folders',
      'lint-filenames',
      'shellcheck',
    ]
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
